### ISSUE TITLE
Main thread required, but write/read disk violation

### ISSUE THREAD

**Issue by Frank1234** [at-internet/piano-analytics-android#11]
If I call `PianoAnalytics.init(...)` on the main thread, I get a `StrictMode.ThreadPolicy` warning because it writes to / reads from disk.

```
StrictMode policy violation; ~duration=40 ms: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:275)
	at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:353)
	at io.piano.android.analytics.PrefsStorage.<init>(PrefsStorage.kt:32)
	at io.piano.android.analytics.DependenciesProvider.<init>(DependenciesProvider.kt:36)
	at io.piano.android.analytics.DependenciesProvider.<init>(Unknown Source:0)
	at io.piano.android.analytics.DependenciesProvider$Companion.init$piano_analytics_release(DependenciesProvider.kt:162)
	at io.piano.android.analytics.PianoAnalytics$Companion.init(PianoAnalytics.kt:177)
	at io.piano.android.analytics.PianoAnalytics$Companion.init$default(PianoAnalytics.kt:172)
```

If I call `PianoAnalytics.init(...)` on Dispatchers.IO, an exception is thrown "java.lang.IllegalStateException: Method addObserver must be called on the main thread" at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded

```
java.lang.IllegalStateException: Method addObserver must be called on the main thread
	at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.kt:296)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:174)
	at io.piano.android.analytics.SessionStorage.addLifecycleObserver$piano_analytics_release(SessionStorage.kt:96)
	at io.piano.android.analytics.SessionStorage.<init>(SessionStorage.kt:60)
	at io.piano.android.analytics.DependenciesProvider.<init>(DependenciesProvider.kt:63)
	at io.piano.android.analytics.DependenciesProvider.<init>(Unknown Source:0)
	at io.piano.android.analytics.DependenciesProvider$Companion.init$piano_analytics_release(DependenciesProvider.kt:162)
	at io.piano.android.analytics.PianoAnalytics$Companion.init(PianoAnalytics.kt:177)
	at io.piano.android.analytics.PianoAnalytics$Companion.init$default(PianoAnalytics.kt:172)
```

Any suggestions, what is best practice here?

**Comment by DeKaN** [comment]
Closing issue due to inactivity. Please feel free to open it again or create a new one and reference this if you have further questions.
