### ISSUE TITLE
App crashes before start

### ISSUE THREAD

**Issue by Zigotote** [at-internet/piano-analytics-android#13]
I am developing a Flutter app, which integrates the analytics Android sdk. I put it in an Android library, which is called inside my app. 
Everything works fine in debug mode, but when I build my app with `flutter build apk` and starts it in a real devices it doesn't work.

I tried to run in a Huawei P8 and have this logs 
<details>
<summary>Huawei logs</summary>

```
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  java.lang.NullPointerException: Attempt to invoke virtual method 'int com.huawei.lcagent.client.LogCollectManager.getUserType()' on a null object reference
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at com.android.server.util.ReportTools.getUserType(ReportTools.java:86)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at com.android.server.util.ReportTools.isBetaUser(ReportTools.java:73)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at com.android.server.util.ReportTools.report(ReportTools.java:58)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at com.android.server.util.HwUserBehaviourRecord.appExitRecord(HwUserBehaviourRecord.java:65)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:1576)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at android.os.Handler.dispatchMessage(Handler.java:102)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at android.os.Looper.loop(Looper.java:150)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at android.os.HandlerThread.run(HandlerThread.java:61)
2023-11-03 10:52:23.678  3436-3452  System.err              system_server                        W  	at com.android.server.ServiceThread.run(ServiceThread.java:46)
2023-11-03 10:52:23.678  3436-3452  ReportTools             system_server                        E  This is not beta user build
2023-11-03 10:52:23.680  5639-5639  Process                 pid-5639                             I  Sending signal. PID: 5639 SIG: 9
2023-11-03 10:52:23.681  4297-4314  PgedBinderListener      com.huawei.powergenie                I  kstate callback type:8 value1=5639 value2=KILLED
2023-11-03 10:52:23.741  4845-4945  DeviceInfoFile          com.huawei.lcagent                   W  !devFile.exists()
```
</details>

With an Oppo Find X2 I have this ones
<details>
<summary>Oppo logs</summary>

```
2023-11-03 11:10:49.879 31575-31575 AndroidRuntime          pid-31575                            E  FATAL EXCEPTION: main
                                                                                                    Process: my.app.dev, PID: 31575
                                                                                                    java.lang.IncompatibleClassChangeError: Class 'android.content.res.XmlBlock$Parser' does not implement interface 'E3.a' in call to 'int E3.a.next()' (declaration of 'androidx.core.content.m' appears in /data/app/my.app.dev-t0sPeqc3LPgxKTco8ldQwg==/base.apk)
                                                                                                    	at androidx.core.content.m.b(SourceFile:20)
                                                                                                    	at androidx.core.content.m.a(SourceFile:1)
                                                                                                    	at androidx.core.content.m.attachInfo(Unknown Source:31)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7545)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7051)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6946)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:255)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2085)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:238)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7937)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:996)
2023-11-03 11:10:49.882  1119-1289  HWComposer              pid-1119                             W  Ignoring duplicate VSYNC event from HWC for display 19261175912888705 (t=374122321517000)
2023-11-03 11:10:49.883  1853-3059  ActivityTaskManager     pid-1853                             W    Force finishing activity my.app.dev/my.app.MainActivity
```
</details>

This is my build.gradle for my customised analytics library
<details>
<summary>build.gradle</summary>

```
group "com.example.analytics"
version "1.0-SNAPSHOT"
buildscript {
    ext.kotlin_version = "1.9.0"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.1.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
apply plugin: "com.android.library"
apply plugin: "kotlin-android"
dependencies {
    implementation "io.piano.android:analytics:3.3.4"
    // Used to import a JsonAdapter for analytics plugin
    implementation "com.squareup.moshi:moshi-kotlin:1.15.0"
}
android {
    namespace "com.example.analytics"
    compileSdk 34
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }
    defaultConfig {
        minSdkVersion 23
    }
}
```
</details>

And this is my PianoAnalytics class
<details>
<summary>Kotlin file</summary>

```
package my.app.analytics_plugin
import android.content.Context
import android.util.Log
import io.piano.android.analytics.Configuration
import io.piano.android.analytics.PianoAnalytics
import io.piano.android.analytics.RawJson
import io.piano.android.analytics.model.Event
import io.piano.android.analytics.model.Property
import io.piano.android.analytics.model.PropertyName
import io.piano.android.analytics.model.VisitorIDType
import java.util.Arrays
import java.util.Collections
class PianoAnalyticsApiImpl(context: Context) {
    private val tag = "PianoAnalytics"
    private val context: Context
    init {
        this.context = context
    }
   fun configure(collectDomain: String, siteId: Long) {
        Log.d(
            tag,
            "configure: $collectDomain $siteId"
        )
        PianoAnalytics.init(
            context,
            Configuration.Builder().collectDomain(collectDomain).site(siteId.toInt()).build()
        )
    }
   fun sendEvent(eventName: String, eventProperties: Map<String, String>) {
        Log.d(
            tag,
            "sendEvent: $eventName $eventProperties"
        )
        PianoAnalytics.getInstance().sendEvents(
            Event.Builder(eventName).properties(eventProperties.entries.map {
                Property(
                    PropertyName(it.key),
                    it.value
                )
            }).build()
        )
    }
}
```
</details>

The plugin is then called from my Flutter app. The gradle file of my Flutter app has these configs : 
- `compileSdk 34`
- `ext.kotlin_version = '1.9.0'`
- `classpath 'com.android.tools.build:gradle:8.1.2'`

Do you have any idea why I can have these strange logs ?

**Comment by DeKaN** [comment]
Hi @Zigotote,

Can you format code/logs to improve readability?
I see `interface 'E3.a' in call to 'int E3.a.next()' (declaration of 'androidx.core.content.m'` in your logs, so you have to find the original name in proguard mapping file as the first step. After that, you should check the output for `./gradlew app:dependencies` and find what version of artifact is used for the class

**Comment by Zigotote** [comment]
Hi @DeKaN,

I formatted my logs, it should be better now.
I don't have proguard in my project et don't find any references to it...

**Comment by DeKaN** [comment]
Check all your gradle scripts, one of them contains this code
```
    buildTypes {
        named("release") {
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
```
Try to set `isMinifyEnabled  = false` for the release build and check on your device. If the app works without crash in this mode, then you should fix your proguard rules

**Comment by DeKaN** [comment]
Closing issue due to inactivity. Please feel free to open it again or create a new one and reference this if you have further questions.
