### ISSUE TITLE
App crashes when SDK tries to cast Long to string in SharedPreferencesImpl

### ISSUE THREAD

**Issue by wizard112** [at-internet/piano-analytics-android#19]
Hi,

Since I upgraded the SDK Piano Analytics to last version 3.4.0 I encounter the following issue : 
The user locks screen and when he unlocks the screen the app crashes, it seems the sdk tries to cast a Long in String.

The stack trace =>
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
                                                                                                    	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
                                                                                                    	at io.piano.analytics.LifecycleStep.lambda$new$0$io-piano-analytics-LifecycleStep(LifecycleStep.java:100)
                                                                                                    	at io.piano.analytics.LifecycleStep$$ExternalSyntheticLambda0.computeMetric(D8$$SyntheticClass:0)
                                                                                                    	at io.piano.analytics.LifecycleStep.newSessionInit(LifecycleStep.java:167)
                                                                                                    	at io.piano.analytics.LifecycleStep.onActivityStarted(LifecycleStep.java:235)
                                                                                                    	at android.app.Application.dispatchActivityStarted(Application.java:405)
                                                                                                    	at android.app.Activity.dispatchActivityStarted(Activity.java:1406)
                                                                                                    	at android.app.Activity.onStart(Activity.java:1922)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:344)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
...

Thank you in advence for your helping.

**Comment by DeKaN** [comment]
Hi @wizard112 , 

`LifecycleStep` class has been replaced by another class in version 3.3.0. Looks like your stack trace is from old version, not from 3.4.0

**Comment by wizard112** [comment]
yes, we found in our module the piano dependency with old version which did not remove, sorry for the inconvinience
thank you @DeKaN

**Comment by wizard112** [comment]
good
